# Generated by Django 4.0.5 on 2022-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cve_criticity',
            field=models.CharField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Urgent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_status',
            field=models.CharField(choices=[(1, 'Nouveau'), (2, 'Archivé')], max_length=1),
        ),
    ]
