# Generated by Django 4.0.5 on 2022-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0002_alter_cve_cve_criticity_alter_cve_cve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cve_criticity',
            field=models.CharField(choices=[('F', 'Faible'), ('M', 'Moyen'), ('U', 'Urgent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_status',
            field=models.CharField(choices=[('N', 'Nouveau'), ('A', 'Archivé')], max_length=1),
        ),
    ]
