# Generated by Django 4.0.5 on 2022-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0005_cve_cve_status_cve_cvss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='_id',
            field=models.TextField(default='...'),
        ),
    ]
